dashboard/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    # URLs para CRUD de Biblioteca
    path('libraries/', views.LibraryListAPIView.as_view(), name='library-list'),
    path('libraries/<int:pk>', views.LibraryDetailAPIView.as_view(), name='library-detail'),

    # URLs para CRUD de Livro
    path('libraries/<int:library_pk>/books', views.BookListAPIView.as_view(), name='book-list'),
    path('libraries/<int:library_pk>/books/<int:pk>', views.BookDetailAPIView.as_view(), name='book-detail'),
]

dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('web.urls')),
]

dashboard/web/urls.py
# urls.py

from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    path('bibliotecas/', views.bibliotecas, name='bibliotecas'),
    path('bibliotecas/<int:biblioteca_id>/livros/', views.livros, name='livros'),
    path('graficos/', views.graficos, name='graficos'),
]

dashboard/api/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


class Library(models.Model):
    name = models.CharField(max_length=100)
    creation_date = models.DateField(auto_now_add=True)
    num_books = models.IntegerField(default=0)


class Book(models.Model):
    library = models.ForeignKey(Library, related_name='books', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    creation_date = models.DateField(auto_now_add=True)


@receiver(post_save, sender=Book)
@receiver(post_delete, sender=Book)
def update_library_num_books(sender, instance, **kwargs):
    library = instance.library
    library.num_books = library.books.count()
    library.save()

dashboard/web/models.py
from django.db import models

# Create your models here.

dashboard/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from .models import Library, Book
from .serializers import LibrarySerializer, BookSerializer

class LibraryListAPIView(generics.ListCreateAPIView):
    """
    Esta classe implementa a API para listar e criar bibliotecas.

    Atributos:
        queryset (QuerySet): Conjunto de consultas para recuperar todas as bibliotecas.
        serializer_class (Serializer): Classe de serializador para serializar/desserializar objetos Library.
    """
    queryset = Library.objects.all()
    serializer_class = LibrarySerializer

class LibraryDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    """
    Esta classe implementa a API para detalhar, atualizar e excluir bibliotecas.

    Atributos:
        queryset (QuerySet): Conjunto de consultas para recuperar todas as bibliotecas.
        serializer_class (Serializer): Classe de serializador para serializar/desserializar objetos Library.
    """
    queryset = Library.objects.all()
    serializer_class = LibrarySerializer

class BookListAPIView(generics.ListCreateAPIView):
    """
    Esta classe implementa a API para listar e criar livros.

    Atributos:
        queryset (QuerySet): Conjunto de consultas para recuperar todos os livros.
        serializer_class (Serializer): Classe de serializador para serializar/desserializar objetos Book.
    """
    queryset = Book.objects.all()
    serializer_class = BookSerializer

class BookDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    """
    Esta classe implementa a API para detalhar, atualizar e excluir livros.

    Atributos:
        queryset (QuerySet): Conjunto de consultas para recuperar todos os livros.
        serializer_class (Serializer): Classe de serializador para serializar/desserializar objetos Book.
    """
    queryset = Book.objects.all()
    serializer_class = BookSerializer

dashboard/web/views.py
from django.shortcuts import render
from api.models import Library, Book
from django.db.models import Count
from datetime import datetime, timedelta

def home(request):
    """
    Renderiza a página inicial.

    Args:
        request (HttpRequest): O objeto HttpRequest que representa a requisição HTTP.

    Returns:
        HttpResponse: A resposta HTTP renderizada.
    """
    return render(request, 'pages/home.html')

def bibliotecas(request):
    """
    Renderiza a página de bibliotecas.

    Args:
        request (HttpRequest): O objeto HttpRequest que representa a requisição HTTP.

    Returns:
        HttpResponse: A resposta HTTP renderizada contendo a lista de bibliotecas.
    """
    bibliotecas = Library.objects.all()
    return render(request, 'pages/bibliotecas.html', {'bibliotecas': bibliotecas})

def livros(request, biblioteca_id):
    """
    Renderiza a página de livros de uma biblioteca específica.

    Args:
        request (HttpRequest): O objeto HttpRequest que representa a requisição HTTP.
        biblioteca_id (int): O ID da biblioteca.

    Returns:
        HttpResponse: A resposta HTTP renderizada contendo a lista de livros da biblioteca especificada.
    """
    livros = Book.objects.filter(library=biblioteca_id)
    return render(request, 'pages/livros.html', {'livros': livros, 'biblioteca_id': biblioteca_id})

def graficos(request):
    """
    Renderiza a página de gráficos.

    Esta função também obtém dados sobre a contagem de livros cadastrados por mês e o número total de livros em cada biblioteca.

    Args:
        request (HttpRequest): O objeto HttpRequest que representa a requisição HTTP.

    Returns:
        HttpResponse: A resposta HTTP renderizada contendo os gráficos e dados relevantes.
    """
    six_months_ago = datetime.now() - timedelta(days=30*6)
    books_per_month = Book.objects.filter(creation_date__gte=six_months_ago).extra({'month': "EXTRACT(month FROM creation_date)"}).values('month').annotate(count=Count('id'))

    libraries = Library.objects.all()

    context = {
        'books_per_month': books_per_month,
        'libraries': libraries,
    }

    return render(request, 'pages/graficos.html', context)

dashboard/web/templates/components/footer.html
<footer class="footer">
    <div class="container">
        <p>&copy; 2024 Seu Projeto. Todos os direitos reservados.</p>
    </div>
</footer>

dashboard/web/templates/components/header.html
<body>
    <header class="header">
        <!-- Aqui você pode incluir o cabeçalho da sua página, se houver -->
        <h1>Gestão de Bibliotecas</h1>
    </header>
</body>
</html>

dashboard/web/templates/components/modal_cadastro_biblioteca.html
<!-- templates/modal_cadastro_biblioteca.html -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>
        <h2>Cadastrar Nova Biblioteca</h2>
        <!-- Formulário de cadastro de biblioteca -->
        <form id="cadastroBibliotecaForm" method="post" action="{% url 'api:library-list' %}">
            {% csrf_token %}
            <label for="name">Nome:</label><br>
            <input type="text" id="name" name="name" required><br>
            <button type="submit">Cadastrar</button>
        </form>
    </div>
</div>

<script>
    // Função para fechar o modal
    function closeModal() {
        document.getElementById("myModal").classList.remove("show");
    }

    // Atualiza a página após o formulário ser enviado com sucesso
    document.getElementById("cadastroBibliotecaForm").addEventListener("submit", function(event) {
        event.preventDefault(); // Impede o envio do formulário padrão

        // Envia o formulário via AJAX para a API de cadastro
        fetch(this.action, {
            method: 'POST',
            body: new FormData(this),
            headers: {
                'X-CSRFToken': '{{ csrf_token }}' // Adiciona o token CSRF ao cabeçalho da requisição
            }
        })
        .then(response => {
            if (response.ok) {
                closeModal(); // Fecha o modal
                location.reload(); // Recarrega a página
            } else {
                // Trate erros de resposta da API, se necessário
                console.error('Erro ao cadastrar biblioteca:', response.statusText);
            }
        })
        .catch(error => {
            console.error('Erro ao cadastrar biblioteca:', error);
        });
    });
</script>

dashboard/web/templates/components/modal_cadastro_livro.html
<!-- templates/modal_cadastro_livro.html -->
<div id="modalCadastroLivro" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModalCadastroLivro()">&times;</span>
        <h2>Cadastrar Novo Livro</h2>
        <!-- Formulário de cadastro de livro -->
        <!-- Formulário de cadastro de livro -->
        <form id="cadastroLivroForm">
            {% csrf_token %}
            <label for="nomeLivro">Nome:</label><br>
            <input type="text" id="nomeLivro" name="name" required><br>  <!-- Renomeie o name para corresponder ao campo do modelo -->
            <input type="hidden" id="bibliotecaId" name="library" required>  <!-- Renomeie o name e adicione o atributo required -->
            <button type="submit">Cadastrar</button>
        </form>
    </div>
</div>

<script>
    // Função para abrir o modal de cadastro de livro
    function openModalCadastroLivro(bibliotecaId) {
        document.getElementById("bibliotecaId").value = bibliotecaId;
        document.getElementById("modalCadastroLivro").classList.add("show");
    }

    // Função para fechar o modal de cadastro de livro
    function closeModalCadastroLivro() {
        document.getElementById("modalCadastroLivro").classList.remove("show");
    }

    // Atualiza a página após o formulário ser enviado com sucesso
    document.getElementById("cadastroLivroForm").addEventListener("submit", function(event) {
        event.preventDefault(); // Impede o envio do formulário padrão

        var id = document.getElementById("bibliotecaId").value;
        var nomeLivro = document.getElementById("nomeLivro").value; // Obtenha o valor do campo de entrada de nome do livro

        // Verifique se o nome do livro não está vazio antes de enviar o formulário
        if (nomeLivro.trim() === "") {
            alert("Por favor, insira um nome para o livro.");
            return;
        }

        // Envia o formulário via AJAX para a API de cadastro
        fetch("{% url 'api:book-list' 0 %}".replace('0', id), {
            method: 'POST',
            body: JSON.stringify({ name: nomeLivro, library: id }),  // Adicione o campo 'library' com o valor de 'id'
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}' // Adiciona o token CSRF ao cabeçalho da requisição
            }
        })
        .then(response => {
            if (response.ok) {
                closeModalCadastroLivro(); // Fecha o modal
                location.reload(); // Recarrega a página
            } else {
                // Trate erros de resposta da API, se necessário
                console.error('Erro ao cadastrar livro:', response.statusText);
            }
        })
        .catch(error => {
            console.error('Erro ao cadastrar livro:', error);
        });
    });

</script>

dashboard/web/templates/components/modal_editar_biblioteca.html
<!-- Componente Modal de Edição de Biblioteca -->
<div id="modalEditarBiblioteca" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModalEdit()">×</span>
        <h2>Editar Biblioteca</h2>
        <div>
            <label for="novoNomeBiblioteca">Novo Nome:</label>
            <input type="text" id="novoNomeBiblioteca" placeholder="Digite o novo nome da biblioteca">
        </div>
        <input type="hidden" id="bibliotecaIdEditar"><br>
        <button onclick="editarBiblioteca()" class="btn-editar">Salvar</button>
    </div>
</div>

<script>
    // Função para abrir o modal de edição de biblioteca e preencher o campo com o nome atual
    function openEditarModal(bibliotecaId, bibliotecaName) {
        document.getElementById('modalEditarBiblioteca').classList.add("show");
        document.getElementById('bibliotecaIdEditar').value = bibliotecaId;
        if (bibliotecaName) {
            document.getElementById('novoNomeBiblioteca').value = bibliotecaName;
        }
    }

    // Função para fechar o modal de edição de biblioteca
    function closeModalEdit() {
        document.getElementById('modalEditarBiblioteca').classList.remove("show");
    }

    // Função para editar o nome da biblioteca
    function editarBiblioteca() {
        var id = document.getElementById('bibliotecaIdEditar').value;
        var novoNome = document.getElementById('novoNomeBiblioteca').value;
        var url = "{% url 'api:library-detail' 0 %}".replace('0', id);

        $.ajax({
            url: url,
            type: 'PUT',
            data: { name: novoNome },
            success: function(result) {
                closeModalEdit(); // Fecha o modal de edição
                window.location.reload(); // Recarrega a página após a edição bem-sucedida
            }
        });
    }
</script>

dashboard/web/templates/components/modal_editar_livro.html
<!-- Componente Modal de Edição de Livro -->
<div id="modalEditarLivro" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModalEdit()">×</span>
        <h2>Editar Livro</h2>
        <div>
            <label for="novoNomeLivro">Novo Nome:</label>
            <input type="text" id="novoNomeLivro" placeholder="Digite o novo nome do livro">
        </div>
        <input type="hidden" id="livroIdEditar">
        <input type="hidden" id="bibliotecaId"><br>
        <button onclick="editarLivro()" class="btn-editar">Salvar</button>
    </div>
</div>

<script>
    // Função para abrir o modal de edição de livro e preencher o campo com o nome atual
    function openEditarModal(livroId, livroName, bibliotecaId) {
        document.getElementById('modalEditarLivro').classList.add("show");
        document.getElementById('livroIdEditar').value = livroId;
        document.getElementById('bibliotecaId').value = bibliotecaId;
        if (livroName) {
            document.getElementById('novoNomeLivro').value = livroName;
        }
    }

    function closeModalEdit() {
        document.getElementById('modalEditarLivro').classList.remove("show");
    }

    // Função para editar o nome do livro
    function editarLivro() {
        var livroId = document.getElementById('livroIdEditar').value;
        var novoNome = document.getElementById('novoNomeLivro').value;
        var libraryId = document.getElementById('bibliotecaId').value; // Obtém o ID da biblioteca da página
        var url = "{% url 'api:book-detail' 0 0 %}".replace('0', libraryId).replace('0', livroId); // Monta a URL com os IDs

        $.ajax({
            url: url,
            type: 'PUT',
            data: { name: novoNome, library: libraryId }, // Adiciona o ID da biblioteca aos dados enviados
            success: function(result) {
                closeModalEdit(); // Fecha o modal após a edição bem-sucedida
                window.location.reload(); // Recarrega a página após a edição bem-sucedida
            }
        });
    }
</script>

dashboard/web/templates/components/modal_visualizar_biblioteca.html
<!-- Componente Modal de Visualização de Biblioteca -->
<div id="modalVisualizarBiblioteca" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">×</span>
        <h2 id="nomeBiblioteca">Visualizar Biblioteca</h2>
        <div class="left-align">
            <p>Nome: <span id="nomeBibliotecaSpan"></span></p>
            <p>Quantidade de Livros: <span id="quantidadeLivros"></span></p>
            <p>Data de Criação: <span id="dataCriacao"></span></p>
            <p>Id: <span id="bibliotecaIdSpan"></span></p>
        </div>
        <input type="hidden" id="bibliotecaId">
        <div class="modal-buttons">
        <button onclick="prepararExclusao()" class="btn-excluir">Excluir Biblioteca</button><br><br>
        <a href="#" onclick="irParaBiblioteca()" class="btn-ir-biblioteca">Ir para Página da Biblioteca</a>
    </div>
</div>

<script>
    function irParaBiblioteca() {
        var bibliotecaId = document.getElementById('bibliotecaIdSpan').innerText;
        var url = "{% url 'web:livros' 0 %}".replace('0', bibliotecaId);
        closeModal();
        window.location.href = url;
    }
</script>

<!-- Componente Modal de Confirmação de Exclusão de Biblioteca -->
<div id="modalConfirmacaoExclusao" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">×</span>
        <h2>Confirmar Exclusão</h2>
        <p>Tem certeza que deseja excluir a biblioteca <span id="nomeBibliotecaExclusao"></span>?</p>
        <button onclick="excluirBiblioteca()" class="btn-confirmar-exclusao">Confirmar Exclusão</button>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    // Função para abrir o modal de visualização de biblioteca e preencher os campos
    function openVisualizarModal(bibliotecaId, bibliotecaName, quantidadeLivros, dataCriacao) {
        document.getElementById('modalVisualizarBiblioteca').classList.add("show");
        document.getElementById('bibliotecaId').value = bibliotecaId;
        document.getElementById('bibliotecaIdSpan').innerText = bibliotecaId;
        document.getElementById('nomeBiblioteca').innerText = bibliotecaName;
        document.getElementById('nomeBibliotecaSpan').innerText = bibliotecaName;
        document.getElementById('quantidadeLivros').innerText = quantidadeLivros;
        document.getElementById('dataCriacao').innerText = dataCriacao;
    }

    // Função para abrir o modal de confirmação de exclusão
    function prepararExclusao() {
        var nomeBiblioteca = document.getElementById('nomeBiblioteca').innerText;
        document.getElementById('nomeBibliotecaExclusao').innerText = nomeBiblioteca;
        document.getElementById('modalConfirmacaoExclusao').classList.add("show");
    }

    // Função para confirmar a exclusão da biblioteca
    function excluirBiblioteca() {
        var id = document.getElementById('bibliotecaId').value;
        var url = "{% url 'api:library-detail' 0 %}".replace('0', id);

        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result) {
                closeModal(); // Fecha o modal de confirmação
                window.location.reload(); // Recarrega a página após a exclusão bem-sucedida
            }
        });
    }

    // Função para fechar qualquer modal
    function closeModal() {
        document.getElementById('modalConfirmacaoExclusao').classList.remove("show");
    }
</script>

dashboard/web/templates/components/modal_visualizar_livro.html
<!-- Componente Modal de Visualização de livro -->
<div id="modalVisualizarlivro" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModalView()">×</span>
        <h2 id="nomelivro">Visualizar livro</h2>
        <div>
            <p>Nome: <span id="nomelivroSpan"></span></p>
            <p>Biblioteca: <span id="bibliotecaSpan"></span></p>
            <p>Data de Criação: <span id="dataCriacao"></span></p>
            <p>Id: <span id="livroIdSpan"></span></p>
        </div>
        <input type="hidden" id="livroId">
        <button onclick="prepararExclusao()" class="btn-excluir">Excluir livro</button>
    </div>
</div>


<!-- Componente Modal de Confirmação de Exclusão de livro -->
<div id="modalConfirmacaoExclusao" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModalDelete()">×</span>
        <h2>Confirmar Exclusão</h2>
        <p>Tem certeza que deseja excluir a livro <span id="nomelivroExclusao"></span>?</p>
        <button onclick="excluirlivro()" class="btn-confirmar-exclusao">Confirmar Exclusão</button>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    // Função para abrir o modal de visualização de livro e preencher os campos
    function openVisualizarModal(livroId, livroName, bibliotecaId, bibliotecaName, dataCriacao) {
        document.getElementById('modalVisualizarlivro').classList.add("show"); // Exibe o modal de visualização de livro
        document.getElementById('livroId').value = livroId;
        document.getElementById('livroIdSpan').innerText = livroId;
        document.getElementById('nomelivro').innerText = livroName;
        document.getElementById('nomelivroSpan').innerText = livroName;
        document.getElementById('bibliotecaSpan').innerText = bibliotecaName;
        document.getElementById('bibliotecaId').value = bibliotecaId;
        document.getElementById('dataCriacao').innerText = dataCriacao;
    }
    function closeModalDelete() {
        document.getElementById('modalConfirmacaoExclusao').classList.remove("show");
    }
    function closeModalView() {
        document.getElementById('modalVisualizarlivro').classList.remove("show");
    }


    // Função para abrir o modal de confirmação de exclusão
    function prepararExclusao() {
        var nomelivro = document.getElementById('nomelivro').innerText;
        document.getElementById('nomelivroExclusao').innerText = nomelivro;
        document.getElementById('modalConfirmacaoExclusao').classList.add("show");

    }
    // Função para confirmar a exclusão da livro
    function excluirlivro() {
        var livroId = document.getElementById('livroId').value;
        var libraryId = document.getElementById('bibliotecaId').value; // Obtém o ID da biblioteca da página
        var url = "{% url 'api:book-detail' 0 0 %}".replace('0', libraryId).replace('0', livroId); // Monta a URL com os IDs

        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result) {
                window.location.reload(); // Recarrega a página após a exclusão bem-sucedida
            }
        });

    }


</script>

dashboard/web/templates/components/navbar.html
<nav class="navbar">
    <div class="container">
        <a href="{% url 'web:home' %}" class="navbar-brand">Home</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'web:bibliotecas' %}" class="nav-link">Bibliotecas</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'web:graficos' %}" class="nav-link">Gráficos</a>
            </li>
        </ul>
    </div>
</nav>

dashboard/web/templates/pages/base.html
<!DOCTYPE html>
{% load static %}
{% include 'components/header.html' %}
{% include 'components/navbar.html' %}




<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Seu Título Aqui{% endblock %}</title>
    <!-- Adicione aqui links para arquivos CSS, JavaScript, etc., se necessário -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal_styles.css' %}">
</head>
<body>

    <!-- Conteúdo da página -->
    <div class="container">
        {% block content %}{% endblock %}
    </div>

</body>
{% include 'components/footer.html' %}
</html>

dashboard/web/templates/pages/bibliotecas.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
    <h1>Bibliotecas</h1>
    <div class="main">


        <!-- Incluindo o modal de cadastro de biblioteca -->
        {% include 'components/modal_cadastro_biblioteca.html' %}

        <!-- Lista de bibliotecas -->
        <div class="bibliotecas">
            <div class="bibliotecas-container">
                <!-- Cabeçalho da lista de bibliotecas -->
                <div class="biblioteca-row">
                    <div class="biblioteca-info">
                        <div class="info-container">
                            <strong>Name</strong>
                        </div>
                        <div class="info-container">
                            <strong>Data de Criação</strong>
                        </div>
                        <div class="info-container">
                            <strong>Número de Livros</strong>
                        </div>
                        <div class="opcoes">
                            <button onclick="openModal()" class="btn btn-adicionar">Adicionar Nova Biblioteca</button>
                        </div>
                    </div>
                </div>
                {% if bibliotecas %}
                    <!-- Loop para exibir as bibliotecas -->
                    {% for biblioteca in bibliotecas %}
                        <div class="biblioteca-row">
                            <div class="biblioteca-info">
                                <!-- Detalhes da biblioteca -->
                                <div class="info-container">
                                    {{ biblioteca.name }}
                                </div>
                                <div class="info-container">
                                    {{ biblioteca.creation_date }}
                                </div>
                                <div class="info-container">
                                    {{ biblioteca.num_books }}
                                </div>
                                <div class="opcoes">
                                    <div class="row">
                                        <button onclick="openVisualizarModal('{{ biblioteca.id }}', '{{ biblioteca.name }}', '{{ biblioteca.num_books}}', '{{ biblioteca.creation_date}}')" class="btn btn-visualizar mr-2 d-inline-block">Visualizar</button>
                                        <button onclick="openEditarModal('{{ biblioteca.id }}', '{{ biblioteca.name }}')" class="btn btn-editar d-inline-block">Editar</button>
                                                                              
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Nenhuma biblioteca encontrada.</p>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Modais -->
    {% include 'components/modal_editar_biblioteca.html' %}
    {% include 'components/modal_visualizar_biblioteca.html' %}

    <!-- Script para abrir e fechar o modal -->
    <script>
        // Função para abrir o modal de cadastro de nova biblioteca
        function openModal() {
            document.getElementById("myModal").classList.add("show");
        }

        // Função para fechar o modal
        function closeModal() {
            document.getElementById("myModal").classList.remove("show");
            document.getElementById("modalEditarBiblioteca").classList.remove("show"); // Fecha o modal de exclusão também
            document.getElementById("modalVisualizarBiblioteca").classList.remove("show"); // Fecha o modal de visualização também
            
        }

        function closeModalConfirm() {
            document.getElementById("modalConfirmacaoExclusao").classList.remove("show");
        }

        // Fechar o modal se o usuário clicar fora dele
        window.onclick = function(event) {
            var modais = document.getElementsByClassName("modal");
            for (var i = 0; i < modais.length; i++) {
                if (event.target == modais[i]) {
                    closeModal();
                }
            }
        }


    </script>
{% endblock %}

dashboard/web/templates/pages/home.html
{% extends 'pages/base.html' %}

{% block title %}Home - Meu Site{% endblock %}

{% block content %}

    <div class="main">
        <div class="main d-flex align-items-center justify-content-center flex-column" style="height: 100vh;">
            <h1 class="mb-4">Bem-vindo à Página Inicial!</h1>
            
            <p class="lead mb-4">Esta página apresenta as funcionalidades disponíveis no projeto.</p>
            
            <section class="mb-4">
                <h2>CRUD Biblioteca</h2>
                <p><strong>Entidade:</strong> Biblioteca</p>
                <p><strong>Campos:</strong> Nome, Data de Criação, Número de Livros Cadastrados</p>
                <p><strong>Operações:</strong> Adicionar, Visualizar Detalhes, Atualizar, Excluir</p>
            </section>
            
            <section class="mb-4">
                <h2>CRUD Livros</h2>
                <p><strong>Entidade:</strong> Livros</p>
                <p><strong>Campos:</strong> Nome, Data de Criação</p>
                <p><strong>Operações:</strong> Adicionar, Visualizar Detalhes, Atualizar, Excluir</p>
            </section>
            
            <section class="mb-4">
                <h2>Gráfico 📈</h2>
            </section>
            
            <div>
                <a href="{% url 'web:bibliotecas' %}" class="btn btn-primary btn-lg">Ver Bibliotecas</a>
            </div>
        </div>
    </div>
{% endblock %}